local addonName, ns = ...
if type(ns) ~= "table" then
  ns = {}
end

-- Generated by scripts/gen_patch_notes.py from CHANGELOG.md. Do not edit by hand.
local PatchNotes = {
  version = "v2.0.3",
  date = "2026-09-26",
  lines = {
    'New "Only auto-open outside combat" option under Options > Behavior. Enabled by default, it keeps incoming whispers from opening the main messenger window during fights when "Auto-open on incoming whisper" is turned on.',
    "The combat option affects only automatic opening of the main window. Messages still arrive and remain saved; you can open the messenger manually, and small message-preview popups keep their existing behavior.",
  },
}

ns.PatchNotes = PatchNotes

return PatchNotes
