local addonName, ns = ...
if type(ns) ~= "table" then
  ns = {}
end

-- Generated by scripts/gen_patch_notes.py from CHANGELOG.md. Do not edit by hand.
local PatchNotes = {
  version = "v2.0.2",
  date = "2026-09-26",
  lines = {
    "WhisperMessenger now supports the original Wrath of the Lich King 3.3.5a client, including Frostmourne/Rebuffed.",
    "Keep the familiar messenger window, themes, chat bubbles, saved conversations, drafts, quick replies, and contact settings.",
    "Character whispers and party, raid, guild, and battleground chats work with the original client. Battleground chat appears in the Groups tab.",
    "Replies, reactions, typing indicators, and read receipts are available between players running compatible copies of the addon.",
    "Fixed: the addon could fail to load on original Wrath, leaving /wmsg unavailable.",
    "Fixed: class icons now show the correct artwork on Frostmourne instead of slices of nearby icons.",
    "Fixed: settings, contact menus, popups, clickable chat links, and notification sounds now work with the original Wrath client.",
    "Fixed: friends and guildmates update their online status using information available from the original client. A player with no known status is not automatically marked offline.",
    "The invite button now directs friends to this Wrath backport.",
    "No extra compatibility addon is required. The backport can also run alongside ClassicAPI.",
    "Battle.net whispers and communities are unavailable on this client. Notification sounds follow your game audio settings.",
  },
}

ns.PatchNotes = PatchNotes

return PatchNotes
